In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/faq-doc/FAQs on Aadhaar.pdf
/kaggle/input/admission-pdf/Admissions-Brochure-2025.pdf


In [2]:
pip install pdfplumber

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pdfplumber

def extract_text_from_pdf(file_path):
    text = ""
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            text += page.extract_text() + "\n"
    return text

In [4]:
pip install PyMuPDF

Note: you may need to restart the kernel to use updated packages.


In [5]:
import fitz  # PyMuPDF

def extract_text_with_pymupdf(pdf_path):
    text = ""
    with fitz.open(pdf_path) as doc:
        for page in doc:
            text += page.get_text()
    return text


In [6]:
extract_text_of_pdf=extract_text_with_pymupdf('/kaggle/input/admission-pdf/Admissions-Brochure-2025.pdf')

In [7]:
import re
from collections import Counter

def clean_and_tokenize(text):
    # Lowercase and remove non-word characters
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s\n]', '', text)
    tokens = text.split()
    return tokens


In [8]:
token_list_pdf=clean_and_tokenize(extract_text_of_pdf)
#token_list_pdf

In [9]:
len(token_list_pdf)

3472

In [10]:
pip install tokenizers

Note: you may need to restart the kernel to use updated packages.


In [11]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers

def train_bpe_tokenizer(tokens, vocab_size=5000, save_path="bpe_tokenizer.json"):
    #tokenizer = Tokenizer(models.WordPiece(unk_token="[UNK]"))
    tokenizer = Tokenizer(models.BPE(unk_token="[UNK]"))
    tokenizer.pre_tokenizer = pre_tokenizers.Whitespace()
    
    #trainer = trainers.WordPieceTrainer(vocab_size=vocab_size, special_tokens=["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"])
    trainer = trainers.BpeTrainer(vocab_size=vocab_size, special_tokens=["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"])
    tokenizer.train_from_iterator(tokens, trainer=trainer)
    
    tokenizer.save(save_path)
    return tokenizer

In [12]:
tokenizer=train_bpe_tokenizer(token_list_pdf,vocab_size=5000, save_path="bpe_tokenizer.json")
tokenizer

Tokenizer(version="1.0", truncation=None, padding=None, added_tokens=[{"id":0, "content":"[PAD]", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":1, "content":"[UNK]", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":2, "content":"[CLS]", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":3, "content":"[SEP]", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":4, "content":"[MASK]", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}], normalizer=None, pre_tokenizer=Whitespace(), post_processor=None, decoder=None, model=BPE(dropout=None, unk_token="[UNK]", continuing_subword_prefix=None, end_of_word_suffix=None, fuse_unk=False, byte_fallback=False, ignore_merges=False, vocab={"[PAD]":0, "[UNK]":1, "[CLS]":2, "[SEP]":3, "[MASK]":4, "0":5, "1":6, "2":7, "3":8, "4":9, "5

In [13]:
from tokenizers import Tokenizer

def encode_text(text, tokenizer_path="bpe_tokenizer.json"):
    tokenizer = Tokenizer.from_file(tokenizer_path)
    encoded = tokenizer.encode(text)
    return encoded.tokens, encoded.ids

In [14]:
sample = "the programme may expand to other streams in the next few years"
bpe_tokens, bpe_ids = encode_text(sample)

print("BPE Tokens:", bpe_tokens)
print("Token IDs:", bpe_ids)

BPE Tokens: ['the', 'programme', 'may', 'expand', 'to', 'other', 'streams', 'in', 'the', 'next', 'few', 'years']
Token IDs: [43, 127, 160, 1380, 85, 866, 418, 41, 43, 1631, 926, 207]


In [15]:
sample = """project evaluation: an assigned faculty mentor, who may be a part of an evaluation committee as specified by the pcc, will be responsible for approving the project goals, for regular evaluation (as per schedule indicated by the pcc), for bringing in the needed academic rigor, and for the final evaluation. a sponsoring company guide will be identified for each student and will monitor internal progress on a regular basis. one guide (from the sponsoring company) can guide at most 6 students. the internal guide shall have a phd or five years' experience post masters. both the faculty mentor for the project and the organisational guide must be identified prior to start of the project."""
bpe_tokens, bpe_ids = encode_text(sample)

print("BPE Tokens:", bpe_tokens)
print("Token IDs:", bpe_ids)

BPE Tokens: ['project', 'evaluation', '[UNK]', 'an', 'assigned', 'faculty', 'mentor', '[UNK]', 'who', 'may', 'be', 'a', 'part', 'of', 'an', 'evaluation', 'committee', 'as', 'specified', 'by', 'the', 'pcc', '[UNK]', 'will', 'be', 'responsible', 'for', 'approving', 'the', 'project', 'goals', '[UNK]', 'for', 'regular', 'evaluation', '[UNK]', 'as', 'per', 'schedule', 'indicated', 'by', 'the', 'pcc', '[UNK]', '[UNK]', 'for', 'bringing', 'in', 'the', 'needed', 'academic', 'rigor', '[UNK]', 'and', 'for', 'the', 'final', 'evaluation', '[UNK]', 'a', 'sponsoring', 'company', 'guide', 'will', 'be', 'identified', 'for', 'each', 'student', 'and', 'will', 'monitor', 'internal', 'progress', 'on', 'a', 'regular', 'basis', '[UNK]', 'one', 'guide', '[UNK]', 'from', 'the', 'sponsoring', 'company', '[UNK]', 'can', 'guide', 'at', 'most', '6', 'students', '[UNK]', 'the', 'internal', 'guide', 'shall', 'have', 'a', 'phd', 'or', 'five', 'years', '[UNK]', 'experience', 'post', 'masters', '[UNK]', 'both', 'the',

In [16]:
extract_text_of_pdf=extract_text_with_pymupdf('/kaggle/input/admission-pdf/Admissions-Brochure-2025.pdf')
text = extract_text_of_pdf.lower()
sample = re.sub(r'[^a-zA-Z0-9\s\n]', '', text)

bpe_tokens, bpe_ids = encode_text(sample)


In [17]:
from tokenizers import Tokenizer

tokenizer = Tokenizer.from_file("bpe_tokenizer.json")
vocab = tokenizer.get_vocab()
type(vocab)


dict

In [18]:
# Reverse the dictionary to index -> token
id_to_token = {idx: token for token, idx in vocab.items()}

# Sort by index
sorted_items = sorted(id_to_token.items())

# Write to file
with open("vocab.txt", "w", encoding="utf-8") as f:
    for idx, token in sorted_items:
        f.write(f"{idx}\t{token}\n")

In [19]:
token_ids =bpe_ids
vocab_size = tokenizer.get_vocab_size()
one_hot = np.eye(vocab_size)[token_ids]
print("Shape:", one_hot.shape)  # (sequence_length, vocab_size)
print("One-hot vectors:\n", one_hot)

Shape: (3472, 1729)
One-hot vectors:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
pip install nltk

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Note: you may need to restart the kernel to use updated packages.


In [21]:
import nltk
nltk.download('punkt')  # only once
from nltk.tokenize import sent_tokenize, word_tokenize


[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [22]:
sentences = sent_tokenize(extract_text_of_pdf)


In [23]:
tokenized_sentences = [word_tokenize(sent.lower()) for sent in sentences]


In [24]:
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('all-MiniLM-L6-v2')




embeddings = model.encode(sentences)


for sent, vector in zip(sentences, embeddings):
    print(f"\nSentence: {sent}")
    print(f"Embedding (dim={len(vector)}):\n{vector[:5]}...")  # Print only first 5 dims for preview


2025-06-15 07:54:12.233865: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1749974052.450645     196 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1749974052.508492     196 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


Batches:   0%|          | 0/7 [00:00<?, ?it/s]


Sentence: M.Tech (Online) Degree Programme
for Working Professionals 
Information Brochure 2025 
M.Tech.
Embedding (dim=384):
[-0.01939494  0.02606472  0.03561768  0.05302649 -0.03412753]...

Sentence: (Online) Degree Programme for Sponsored Candidates
In the spirit of India's National Education Policy (NEP 2020), the Indian Institute of Science (IISc), 
Bengaluru, launched the Master of Technology (Online) degree in 2021 as a fully-online programme, for 
practicing technologists, engineers and scientists.
Embedding (dim=384):
[-0.07217079  0.04848374  0.03610421  0.02126717  0.01107701]...

Sentence: The programme is designed for professionals who 
already have a BE, BTech or equivalent degree and wish to upskill or re-skill.
Embedding (dim=384):
[-0.00187683 -0.01107489  0.01589023  0.0048186  -0.03181972]...

Sentence: This is a sponsored program, 
where organisations having an MoA with IISc may nominate their employees.
Embedding (dim=384):
[-0.12443674  0.01858643  0.02108258 -0.

In [25]:
!pip install opentelemetry-api==1.27.0 opentelemetry-sdk==1.27.0 opentelemetry-exporter-otlp-proto-grpc==1.27.0 protobuf==3.20.3



huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [26]:
pip install --upgrade chromadb


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Note: you may need to restart the kernel to use updated packages.


In [27]:
from chromadb.config import Settings
import chromadb
settings = Settings(allow_reset=True, anonymized_telemetry=False)

client = chromadb.Client(settings)

In [28]:

#client = chromadb.Client(Settings(chroma_db_impl="duckdb+parquet", persist_directory="./chroma_store"))
collection = client.get_or_create_collection(name="my_document")

In [29]:
collection.add(
    documents=sentences,
    embeddings=embeddings.tolist(),     # convert numpy to list
    ids=[f"id_{i}" for i in range(len(sentences))]
)

In [30]:
query = "How many course are offered in 2025"
query_embedding = model.encode([query]).tolist()[0]
results = collection.query(
    query_embeddings=[query_embedding],
    n_results=3,
    include=["documents", "metadatas", "embeddings", "distances"]
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [31]:
results

{'ids': [['id_149', 'id_117', 'id_49']],
 'embeddings': [array([[ 0.00589292, -0.04098699, -0.02275125, ..., -0.01909672,
           0.01455601,  0.0111619 ],
         [ 0.01514556, -0.0873604 , -0.03316682, ..., -0.02039055,
          -0.0346375 ,  0.00066837],
         [-0.04259327, -0.05701727,  0.04909712, ..., -0.02538515,
          -0.02475414, -0.01577348]])],
 'documents': [['This is until course requirements\nare completed.',
   'Core course can be between 9-16 credits and will be specified by the PCC.',
   'Additional Stream-specific Eligibility Criteria \nTentative Schedule for 2025 Academic Year (Starting 1st August 2025) \nApplications Portal Opens \n14 March, 2025 \nApplications Portal Closes \n01 April, 2025 \nOnline Written Test & Interviews \n03- 04 May, 2025 \nOffer of Admission to Selected Candidates \n07 June, 2025 \nPayment of Fees & Deposit by Selected Candidates \n14 June, 2025 \nClasses Start for Academic Year \n1 August, 2025 \nStream \nPrior Degree \nMinimum \

In [32]:
def query_pdf(question):
    query_embedding = model.encode([question]).tolist()
    results = collection.query(query_embeddings=query_embedding, n_results=5)
    
    context = "\n".join(results["documents"][0])
    
    prompt = f"""Answer the question using only the context below. Be concise.

Context:
{context}

Question:
{question}

Answer:"""
    
    return prompt


In [33]:
from transformers import AutoTokenizer, AutoModelForCausalLM
access_token = "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"
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1",token=access_token)
modelMM = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1",token=access_token)

inputs = tokenizer(query_pdf("What is the evaluation process?"), return_tensors="pt")
outputs = modelMM.generate(**inputs, max_new_tokens=200)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


Answer the question using only the context below. Be concise.

Context:
Assessment: Evaluation is based on instructors' assessment plan which will be pre- approved by the senate
curriculum committee (which approves the course).
Project evaluation: An assigned faculty mentor, who may be a part of an evaluation committee as specified
by the PCC, will be responsible for approving the project goals, for regular evaluation (as per schedule
indicated by the PCC), for bringing in the needed academic rigor, and for the final evaluation.
Assessments will be based on online examinations and evaluations, unless noted otherwise.
This will evaluate the technical ability of the candidate to succeed
in the coursework and may include topics such as mathematics, basic programming, problem-solving,
etc.
This will evaluate the technical ability of the candidate to succeed
in the coursework and may include topics such as mathematics, basic programming, problem-solving,
etc.

Question:
What is the evaluati